---
abstract: 'Object-oriented module for HTML form input validation and display'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Form
provides:
  WWW::FieldValidator:
    file: lib/WWW/FieldValidator.pm
    version: 1.19
  WWW::Form:
    file: lib/WWW/Form.pm
    version: 1.19
requires:
  CGI: 0
  Data::Dumper: 0
  constant: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-Form
  repository: https://bitbucket.org/shlomif/perl-www-form
version: 1.19
